import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import style from './layout.module.css';
import {BookData} from "@/types";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function Footer(){
  /*const response = await fetch(`${process.env.NEXT_PUBLIC_API_SERVER_URL}/book`,{cache:"force-cache"})
  if(!response.ok){
    return <footer>제작 @ilovepc</footer>
  }
  const books : BookData[] = await response.json();*/
  //const length = books.length;
  const length = 10;
  return (
      <footer>
        <div>제작 @ilovepc</div>
        <div>{length}개의 도서가 등록되어있음</div>
      </footer>
  )
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className={style.container}>
          <header>
            <Link href={'/'}>📚 ONEBITE BOOKS</Link>
          </header>
          <main>{children}</main>
          <Footer/>
        </div>
      </body>
    <div id="modal-root"></div>
    </html>
  );
}
